apiVersion: v1
kind: ConfigMap
data:
  additionalDatasources.yaml: |-
    apiVersion: 1
    datasources:
    {{- range .Values.additionalDataSources }}
    - {{ toYaml . | indent 6 | trim }}
    {{- end }}
metadata:
  name: {{ .Chart.Name }}-datasources
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "grafana-configs.name" $ }}
{{ include "grafana-configs.labels" $ | indent 4 }}
{{- range $key, $value := .Values.datasources.label }}
{{ $key | indent 4 }}: {{ $value | quote }}
{{- end }}