druid_env: "${deployment_stage}"
druid_cluster_type: "raw"
druid_image: "apache/druid:0.21.1"
druid_namespace: "${druid_namespace}"
dp_vault_pgdb_admin_password: postgres
druid_monitoring: False
mount_path: /druid/data
storageClass: ${storage_class_name}

######################### Druid common variables ########################
druid_directory: "/opt/druid"
druid_extensions_loadList: '"postgresql-metadata-storage", "druid-kafka-indexing-service"'

# Logging
# Log all runtime properties on startup. Disable to avoid logging properties on startup:
druid.startup.logging.logProperties: true

# Druid Metadata Store
druid_metadata_storage_type: "postgresql"
druid_metadata_storage_connector_connectURI: "jdbc:postgresql://postgresql-hl.postgresql.svc.cluster.local:5432/druid_raw"
druid_metadata_storage_connector_user: "${druid_user}"
druid_metadata_storage_connector_password: "${druid_password}"

# Druid Storage Type
druid_deepstorage_type: "local"
druid_storage_directory: "/data"

# Indexing service logs
# For local disk (only viable in a cluster_type if this is a network mount):
druid_indexer_logs_type: "file"
druid_indexer_logs_prefix: "druid-task-logs"

# Service discovery
druid_selectors_indexing_serviceName: druid/overlord
druid_selectors_coordinator_serviceName: druid/coordinator

# Monitoring
druid_monitoring_monitors: '"com.metamx.metrics.JvmMonitor","org.apache.druid.java.util.metrics.JvmMonitor"'
druid_emitter: composing
druid_emitter_composing_emitters: '"logging"'
druid_emitter_logging_logLevel: INFO


# Storage type of double columns
# ommiting this will lead to index double as float at the storage layer
druid_indexing_doubleStorage: double

#Writing query logs into file 
druid_request_logging_type: composing
druid_request_logging_dir: "/var/log/druid/"

druid_javascript_enabled: true
druid_sql_enable: true

####################### Druid Broker Variables ##########################

druid_broker_service: druid/broker
druid_broker_port: 8082
druid_broker_min_heap_size: 128M
druid_broker_max_heap_size: 128M
druid_broker_max_direct_size: 800M

# HTTP server threads
druid_broker_http_numConnections: 5
druid_server_http_numThreads: 25

# Processing threads and buffers
druid_broker_processing_buffer_sizeBytes: 128MiB
druid_broker_processing_numThreads: 2

druid_javascript.enabled: true
druid_sql_enable: true

druid_broker_replicas: 1

##################### Druid Coordinator Variables #######################

druid_coordinator_service: druid/coordinator
druid_coordinator_port: 8081
druid_coordinator_heap_size: 128M

druid_coordinator_startDelay: PT30S
druid_coordinator_period: PT30S
druid_coordinator_balancer_strategy: diskNormalized

druid_coordinator_replicas: 1

####################### Druid Overlord Variables ########################

druid_overlord_service: druid/overlord
druid_overlord_port: 8090
druid_overlord_heap_size: 256M

druid_indexer_queue_startDelay: PT30S

druid_indexer_runner_type: remote
druid_indexer_storage_type: metadata

# Additional parameters for minor compaction
druid_indexer_tasklock_forceTimeChunkLock: false

druid_overlord_replicas: 1

###################### Druid Historical Variables #######################

druid_historical_service: druid/historical
druid_historical_port: 8084
druid_historical_min_heap_size: 512M
druid_historical_max_heap_size: 512M
druid_historical_max_direct_size: 800M

# HTTP server threads
druid_server_http_numThreads: 25

# Processing threads and buffers
druid_historical_processing_buffer_sizeBytes: 128MiB
druid_historical_processing_numThreads: 2
druid_historical_processing_numMergeBuffers: 2

druid_query_ondiskstorage_enabled: True
druid_query_groupBy_maxMergingDictionarySize: 100000000
druid_query_groupBy_maxOnDiskStorage: 1073741824

# Segmentstorage
druid_segmentCache_locations: '{"path": "/var/segments/store0", "maxSize": 2000000000}, {"path": "/var/segments/store1", "maxSize": 2000000000}, {"path": "/var/segments/store2", "maxSize": 2000000000}, {"path": "/var/segments/store3", "maxSize": 2000000000}, {"path": "/var/segments/store4", "maxSize": 2000000000}'

druid_historical_persistent_volume_size: 1G

druid_segmentCache_numLoadingThreads: 4

# Caching
druid_historical_cache_useCache: False 
druid_historical_cache_populateCache: true
druid_historical_cache_unCacheable: '"select", "scan"'
druid_cache_type: caffeine
druid_historical_cache_size: 256MiB
druid_historical_cache_expiry: 3600000

druid_historical_replicas: 1

#################### Druid Middlemanager Variables ######################

druid_middlemanager_service: druid/middlemanager
druid_middlemanager_port: 8091
druid_middlemanager_heap_size: 128M

druid_middlemanager_persistent_volume_size: 1G

# Number of tasks per middleManager
druid_worker_capacity: "${druid_worker_capacity}"
druid_middlemanager_peon_heap_size: 256M

# Task launch parameters
druid_indexer_runner_javaOpts: "-server -Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
druid_indexer_task_baseTaskDir: "/var/task"

# Peon properties
druid_indexer_fork_property_druid_processing_buffer_sizeBytes: 25MiB
druid_indexer_fork_property_druid_processing_numThreads: 2
druid_indexer_fork_property_druid_server_http_numThreads: 25

#Additional Parameters
druid_indexer_task_restoreTasksOnRestart: true

druid_middlemanager_replicas: 1

######################## Druid Router Variables #########################

druid_router_service: druid/router
druid_router_plaintextPort: 8888
druid_router_heap_size: 512M

# HTTP proxy
druid_router_http_numConnections: 50
druid_router_http_readTimeout: PT5M
druid_router_http_numMaxThreads: 100
druid_server_http_numThreads: 100

# Service discovery
druid_router_defaultBrokerServiceName: druid/broker
druid_router_coordinatorServiceName: druid/coordinator

# Management proxy to coordinator / overlord: required for unified web console.
druid_router_managementProxy_enabled: True

druid_router_replicas: 1

#################### Zookeeper Variables ######################

zookeeper:
  image:
    registry: docker.io
    repository: bitnami/zookeeper
    tag: 3.6-debian-10
    pullPolicy: Always

  persistence:
    size: 1Gi

  heapSize: 128
  replicaCount: 1

  resources:
    requests:
      memory: 128Mi
      cpu: 512m

  tickTime: 2000
  initLimit: 10
  syncLimit: 5
  preAllocSize: 65536
  snapCount: 100000
  maxClientCnxns: 60
  fourlwCommandsWhitelist: srvr, mntr, ruok
  listenOnAllIPs: false
  allowAnonymousLogin: true
  autopurge:
    snapRetainCount: 3
    purgeInterval: 0
  maxSessionTimeout: 40000

  allowAnonymousLogin: true

  minServerId: 1

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    probeCommandTimeout: 2

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    probeCommandTimeout: 2

  service:
    type: ClusterIP
    # loadBalancerIP: ""
    port: 2181
    followerPort: 2888
    electionPort: 3888
    nodePorts:
      client: ""
      clientTls: ""
    publishNotReadyAddresses: true
    tlsClientPort: 3181
    disableBaseClientPort: false
    annotations: {}
    headless:
      annotations: {}
    
    
  