namespace: "submit-ingestion"
druid_router_host: "druid-raw-routers.druid-raw.svc.cluster.local:8888"
supervisor_path: "druid/indexer/v1/supervisor"
bootstrap_servers: "kafka-headless.kafka.svc.cluster.local:9092"
ingestion_spec:
  system_stats:
    topic: "sb-dev.stats"
    name: "system-stats"
  masterdata_system_stats:
    topic: "sb-dev.masterdata.stats"
    name: "masterdata-system-stats"
  failed_events:
    topic: "sb-dev.failed"
    name:  "failed-events"
  masterdata_failed_events:
    topic: "sb-dev.masterdata.failed"
    name:  "masterdata-failed-events"  