---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-taskmanager
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Release.Name }}-taskmanager
    release: monitoring
spec:
  selector:
    matchLabels:
      component: {{ .Release.Name }}-jobmanager
  endpoints:
  - port: prom
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-jobmanager
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Release.Name }}-jobmanager
    release: monitoring
spec:
  selector:
    matchLabels:
      component: {{ .Release.Name }}-jobmanager
  endpoints:
  - port: prom
    interval: 30s