apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-spec-config
  namespace: {{ .Values.namespace }}
data:
  system-stats-ingestion-spec.json: |-
    {
      "type": "kafka",
      "spec": {
        "dataSchema": {
          "dataSource": "{{ .Values.ingestion_spec.system_stats.name }}",
          "dimensionsSpec": {
            "dimensions": [
              {
                "type": "string",
                "name": "dataset"
              },
              {
                "type": "boolean",
                "name": "extractor_job_status"
              },
              {
                "type": "boolean",
                "name": "event_validator_job_status"
              },
              {
                "type": "boolean",
                "name": "deduplication_job_status"
              },
              {
                "type": "boolean",
                "name": "transformer_job_status"
              },
              {
                "type": "boolean",
                "name": "denorm_job_status"
              }
            ]
          },
          "timestampSpec": {
            "column": "sync_ts",
            "format": "auto"
          },
          "metricsSpec": [
            {
              "type": "count",
              "name": "count"
            },
            {
              "type": "doubleSum",
              "name": "total_processing_time",
              "fieldName": "total_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "latency_time",
              "fieldName": "latency_time"
            },
            {
              "type": "doubleSum",
              "name": "processing_time",
              "fieldName": "processing_time"
            },
            {
              "type": "doubleSum",
              "name": "extractor_job_processing_time",
              "fieldName": "extractor_job_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "event_validator_job_processing_time",
              "fieldName": "event_validator_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "transformer_job_processing_time",
              "fieldName": "transformer_processing_time"
            }
          ],
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "hour",
            "rollup": true
          }
        },
        "tuningConfig": {
          "type": "kafka",
          "maxRowsPerSegment": 5000000,
          "logParseExceptions": true
        },
        "ioConfig": {
          "type": "kafka",
          "topic": "{{ .Values.ingestion_spec.system_stats.topic }}",
          "consumerProperties": {
            "bootstrap.servers": "{{ .Values.bootstrap_servers }}"
          },
          "taskCount": "1",
          "replicas": 1,
          "taskDuration": "PT1H",
          "useEarliestOffset": false,
          "completionTimeout": "PT1H",
          "inputFormat": {
            "type": "json",
            "flattenSpec": {
              "useFieldDiscovery": false,
              "fields": [
                {
                  "type": "path",
                  "name": "sync_ts",
                  "expr": "$.obsrv_meta.syncts"
                },
                {
                  "type": "path",
                  "name": "dataset",
                  "expr": "$.dataset"
                },
                {
                  "type": "path",
                  "name": "deduplication_job_processing_time",
                  "expr": "$.obsrv_meta.timespans.Deduplication"
                },
                {
                  "type": "path",
                  "name": "denorm_job_processing_time",
                  "expr": "$.obsrv_meta.timespans.DenormalizerJob"
                },
                {
                  "type": "path",
                  "name": "extractor_job_processing_time",
                  "expr": "$.obsrv_meta.timespans.ExtractorJob"
                },
                {
                  "type": "path",
                  "name": "total_processing_time",
                  "expr": "$.obsrv_meta.total_processing_time"
                },
                {
                  "type": "path",
                  "name": "latency_time",
                  "expr": "$.obsrv_meta.latency_time"
                },
                {
                  "type": "path",
                  "name": "processing_time",
                  "expr": "$.obsrv_meta.processing_time"
                },
                {
                  "type": "path",
                  "name": "transformer_processing_time",
                  "expr": "$.obsrv_meta.timespans.TransformerJob"
                },
                {
                  "type": "path",
                  "name": "event_validator_processing_time",
                  "expr": "$.obsrv_meta.timespans.EventValidation"
                },
                {
                  "type": "path",
                  "name": "deduplication_job_status",
                  "expr": "$.obsrv_meta.flags.Deduplication"
                },
                {
                  "type": "path",
                  "name": "extractor_job_status",
                  "expr": "$.obsrv_meta.flags.ExtractorJob"
                },
                {
                  "type": "path",
                  "name": "transformer_job_status",
                  "expr": "$.obsrv_meta.flags.TransformerJob"
                },
                {
                  "type": "path",
                  "name": "event_validator_job_status",
                  "expr": "$.obsrv_meta.flags.EventValidation"
                },
                {
                  "type": "path",
                  "name": "denorm_job_status",
                  "expr": "$.obsrv_meta.flags.DenormalizerJob"
                }
              ]
            }
          },
          "appendToExisting": false
        }
      }
    }
  masterdata-system-stats-ingestion-spec.json: |-
    {
      "type": "kafka",
      "spec": {
        "dataSchema": {
          "dataSource": "{{ .Values.ingestion_spec.masterdata_system_stats.name }}",
          "dimensionsSpec": {
            "dimensions": [
              {
                "type": "string",
                "name": "dataset"
              },
              {
                "type": "boolean",
                "name": "extractor_job_status"
              },
              {
                "type": "boolean",
                "name": "event_validator_job_status"
              },
              {
                "type": "boolean",
                "name": "deduplication_job_status"
              },
              {
                "type": "boolean",
                "name": "transformer_job_status"
              }
            ]
          },
          "timestampSpec": {
            "column": "sync_ts",
            "format": "auto"
          },
          "metricsSpec": [
            {
              "type": "count",
              "name": "count"
            },
            {
              "type": "doubleSum",
              "name": "total_processing_time",
              "fieldName": "total_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "extractor_job_processing_time",
              "fieldName": "extractor_job_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "event_validator_job_processing_time",
              "fieldName": "event_validator_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "transformer_job_processing_time",
              "fieldName": "transformer_processing_time"
            }
          ],
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "hour",
            "rollup": true
          }
        },
        "tuningConfig": {
          "type": "kafka",
          "maxRowsPerSegment": 5000000,
          "logParseExceptions": true
        },
        "ioConfig": {
          "type": "kafka",
          "topic": "{{ .Values.ingestion_spec.masterdata_system_stats.topic }}",
          "consumerProperties": {
            "bootstrap.servers": "{{ .Values.bootstrap_servers }}"
          },
          "taskCount": "1",
          "replicas": 1,
          "taskDuration": "PT1H",
          "useEarliestOffset": true,
          "completionTimeout": "PT1H",
          "inputFormat": {
            "type": "json",
            "flattenSpec": {
              "useFieldDiscovery": false,
              "fields": [
                {
                  "type": "path",
                  "name": "sync_ts",
                  "expr": "$.obsrv_meta.syncts"
                },
                {
                  "type": "path",
                  "name": "dataset",
                  "expr": "$.dataset"
                },
                {
                  "type": "path",
                  "name": "prev_processing_time",
                  "expr": "$.obsrv_meta.flags.prevProcessingTime"
                },
                {
                  "type": "path",
                  "name": "deduplication_job_processing_time",
                  "expr": "$.obsrv_meta.timespans.Deduplication"
                },
                {
                  "type": "path",
                  "name": "extractor_job_processing_time",
                  "expr": "$.obsrv_meta.timespans.ExtractorJob"
                },
                {
                  "type": "path",
                  "name": "total_processing_time",
                  "expr": "$.obsrv_meta.timespans.total_processing_time"
                },
                {
                  "type": "path",
                  "name": "transformer_processing_time",
                  "expr": "$.obsrv_meta.timespans.TransformerJob"
                },
                {
                  "type": "path",
                  "name": "event_validator_processing_time",
                  "expr": "$.obsrv_meta.timespans.EventValidation"
                },
                {
                  "type": "path",
                  "name": "deduplication_job_status",
                  "expr": "$.obsrv_meta.flags.Deduplication"
                },
                {
                  "type": "path",
                  "name": "extractor_job_status",
                  "expr": "$.obsrv_meta.flags.ExtractorJob"
                },
                {
                  "type": "path",
                  "name": "transformer_job_status",
                  "expr": "$.obsrv_meta.flags.TransformerJob"
                },
                {
                  "type": "path",
                  "name": "event_validator_job_status",
                  "expr": "$.obsrv_meta.flags.EventValidation"
                }
              ]
            }
          },
          "appendToExisting": false
        }
      }
    }
