apiVersion: batch/v1
kind: Job
metadata:
  name: submit-ingestion
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: druid
          image: "ubuntu:20.04"
          command:
            - sh
            - -c
            - "apt-get update && apt-get install -y curl && curl -XPOST -H 'Content-Type: application/json' -d @/etc/ingestion-spec/system-stats-ingestion-spec.json http://{{ .Values.druid_router_host }}/{{ .Values.supervisor_path }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/ingestion-spec
      volumes:
        - name: config-volume
          configMap:
            name: ingestion-spec-config
