namespace: "dev"
dockerhub: "sanketikahub"
replicaCount: 1
repository: "obsrv-api-service"
image_tag: 1.0.4
network:
  port: 3000
  targetport: 3000
SYSTEM_ENV: ""
TELEMETRY_KAFKA_COMPRESSION: snappy
druid_service:
  DRUID_HOST: http://druid-raw-routers.druid-raw.svc
  DRUID_PORT: 8888
kafka_service:
  KAFKA_HOST: "kafka-headless.kafka.svc"
  KAFKA_PORT: 9092
  KAFKA_INITIAL_RETRY_TIME: 3000
  KAFKA_RETRIES: 5
  KAFKA_CONNECTION_TIMEOUT: 5000
  CLIENT_ID: "obsrv-apis"
postgres_service:
  POSTGRES_HOST: postgresql-hl.postgresql.svc
  POSTGRES_PORT: 5432
  POSTGRES_DATABASE: "obsrv"
  POSTGRES_USERNAME: "obsrv"
  POSTGRES_PASSWORD: "obsrv123"
redis_service:
  REDIS_HOST: obsrv-redis-headless.redis.svc.cluster.local
  REDIS_PORT: 6379

service_account_annotations: ""