apiVersion: v2
appVersion: 0.11.1
description: A Helm chart for prometheus postgres-exporter
home: https://github.com/prometheus-community/postgres_exporter
keywords:
- postgresql
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
name: prometheus-postgres-exporter
sources:
- https://github.com/prometheus-community/postgres_exporter
type: application
version: 4.2.1
